{"name": "test_multiply", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1\n +  where 2 = multiply(1, 2)\n +    where multiply = <calculator.Calculator object at 0x70dba876c2b0>.multiply", "trace": "self = <test_calculator.TestCalculator object at 0x70dba9c47dc0>, calculator = <calculator.Calculator object at 0x70dba876c2b0>\n\n    def test_multiply(self, calculator):\n        assert calculator.multiply(3, 5) == 15\n        assert calculator.multiply(-2, 3) == -6\n        assert calculator.multiply(0, 5) == 0\n        print(\">> Multiplying \")\n>       assert calculator.multiply(1,2) == 1\nE       assert 2 == 1\nE        +  where 2 = multiply(1, 2)\nE        +    where multiply = <calculator.Calculator object at 0x70dba876c2b0>.multiply\n\ntests/test_calculator.py:29: AssertionError"}, "attachments": [{"name": "stdout", "source": "a1990317-8ca3-4e74-97c4-e18025ae3811-attachment.txt", "type": "text/plain"}], "start": 1740486533874, "stop": 1740486533876, "uuid": "4958c5c2-c511-42ed-a3bb-de2a6a994527", "historyId": "f51238d70696680e766b3c9e6b0f790f", "testCaseId": "f51238d70696680e766b3c9e6b0f790f", "fullName": "tests.test_calculator.TestCalculator#test_multiply", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "PF3HRSSZ"}, {"name": "thread", "value": "304975-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calculator"}]}