{"name": "test_multiply", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1\n +  where 2 = multiply(1, 2)\n +    where multiply = <calculator.Calculator object at 0x7bb1e7aa51b0>.multiply", "trace": "self = <test_calculator.TestCalculator object at 0x7bb1e790abc0>, calculator = <calculator.Calculator object at 0x7bb1e7aa51b0>\n\n    def test_multiply(self, calculator):\n        assert calculator.multiply(3, 5) == 15\n        assert calculator.multiply(-2, 3) == -6\n        assert calculator.multiply(0, 5) == 0\n>       assert calculator.multiply(1,2) == 1\nE       assert 2 == 1\nE        +  where 2 = multiply(1, 2)\nE        +    where multiply = <calculator.Calculator object at 0x7bb1e7aa51b0>.multiply\n\ntests/test_calculator.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "e34ed34a-0ea0-40b7-8356-cc1ec20ebe45-attachment.txt", "type": "text/plain"}], "start": 1740485993454, "stop": 1740485993456, "uuid": "43a1d503-bb93-4bf8-84ad-ea2d25d85230", "historyId": "f51238d70696680e766b3c9e6b0f790f", "testCaseId": "f51238d70696680e766b3c9e6b0f790f", "fullName": "tests.test_calculator.TestCalculator#test_multiply", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "PF3HRSSZ"}, {"name": "thread", "value": "299228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calculator"}]}